AWSTemplateFormatVersion: '2010-09-09'
Description: Secure Patient Record VPC with SNS and EC2

Resources:
  MyVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      Tags:
        - Key: Name
          Value: PatientVPC

  MySubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MyVPC
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: !Select [0, !GetAZs '']

  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0c02fb55956c7d316  # Use latest Amazon Linux AMI ID in your region
      SubnetId: !Ref MySubnet
      Tags:
        - Key: Name
          Value: PatientEC2

  MySNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: PatientReportsTopic

Outputs:
  VPCId:
    Value: !Ref MyVPC
  InstanceId:
    Value: !Ref MyInstance
  SNSTopic:
    Value: !Ref MySNSTopic
